<a href="https://colab.research.google.com/github/rdpambhar/Deep_Learning/blob/main/Deep_Learning/ANN/Energy%20Consumption/Energy_generation_prediction_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.7.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
df=pd.read_excel('Folds5x2_pp.xlsx')
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values
y

array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28])

### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [ ]:
print(len(X_train))
print(len(X_test))


7654
1914


In [ ]:
# from sklearn.preprocessing import StandardScaler
# sc=StandardScaler()
# X_test=sc.fit_transform(X_test)
# X_train=sc.fit_transform(X_train)

## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
model=tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:
model.add(tf.keras.layers.Dense(units=16,activation='relu'))

### Adding the second hidden layer

In [ ]:
model.add(tf.keras.layers.Dense(units=32,activation='relu'))

### Adding the output layer

In [ ]:
model.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),loss=tf.keras.losses.MeanSquaredError())

### Training the ANN model on the Training set

In [ ]:
model.fit(x=X_train,y=y_train,batch_size=32,epochs=100)

Epoch 1/100
240/240 [==============================] - 1s 3ms/step - loss: 19.5612
Epoch 2/100
240/240 [==============================] - 1s 4ms/step - loss: 19.3448
Epoch 3/100
240/240 [==============================] - 1s 3ms/step - loss: 19.7395
Epoch 4/100
240/240 [==============================] - 1s 4ms/step - loss: 19.3464
Epoch 5/100
240/240 [==============================] - 1s 3ms/step - loss: 19.6540
Epoch 6/100
240/240 [==============================] - 1s 3ms/step - loss: 19.4004
Epoch 7/100
240/240 [==============================] - 1s 3ms/step - loss: 19.5529
Epoch 8/100
240/240 [==============================] - 1s 3ms/step - loss: 19.5841
Epoch 9/100
240/240 [==============================] - 1s 3ms/step - loss: 19.2341
Epoch 10/100
240/240 [==============================] - 1s 3ms/step - loss: 19.1392
Epoch 11/100
240/240 [==============================] - 1s 5ms/step - loss: 19.4414
Epoch 12/100
240/240 [==============================] - 1s 4ms/step - loss: 19.4566
E

### Predicting the results of the Test set

In [ ]:
y_predict=model.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_predict.reshape(len(y_predict),1),y_test.reshape(len(y_test),1)),1))
# print(y_test-y_predict)

[[432.07 431.23]
 [457.36 460.01]
 [461.8  461.14]
 ...
 [468.82 473.26]
 [439.96 438.  ]
 [460.57 463.28]]


In [ ]:
model.predict([[8.34,40.77,1010.84,90.01]])

array([[35479.36]], dtype=float32)